name: BioIR-csd
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 42

datasets:
  train:
    name: TrainSet
    type: PairedImageDataset
    dataroot_gt: ./datasets/CSD/train2500/Gt
    dataroot_lq: ./datasets/CSD/train2500/Snow

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: PairedImageDataset
    dataroot_gt: ./datasets/CSD/test2000/Gt
    dataroot_lq: ./datasets/CSD/test2000/Snow
    io_backend:
      type: disk


network_g:
  type: BioIR
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [3,3,6]
  num_refinement_blocks: 4
  ffn_expansion_factor: 3
  bias: False


# path
path:
  pretrain_network_g:
  strict_load_g:
  resume_state: 

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 300000
    eta_min: !!float 1e-7

  total_iter: 300000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_loss_opt:
    type: FFTLoss
    loss_weight: 0.1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: false


  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

